import type { Metadata } from 'next'
import React from 'react'
import { GlobalStyle } from '../lib/theme'
import { Providers } from '../components/providers'
import 'intersection-observer'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1.0,
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <GlobalStyle />
          {children}
        </Providers>
      </body>
    </html>
  )
}
