import type { Metadata } from 'next'
import 'intersection-observer'
import { Providers } from '../components/providers'
import { GlobalStyle } from '../lib/theme'
import '../components/NotificationsContainer'

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1.0',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <GlobalStyle />
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
